x=read.csv(file.choose())
ts1=ts(x$FI,frequency = 1)
plot.ts(ts1)
library("TTR")
library("astsa")
library("forecast")
library(tseries)
adf.test(diff(ts1),alternative = "stationary")
#Since p value is greater than 0.05, the time series is said to be non-stationary.
acf2(ts1)
Box.test(diff(ts1),lag = 15,type = "Ljung-Box")
acf2(diff(ts1))
ndiffs(ts1)
diff(ts1, differences= 1)
library("TTR")
library("forecast")
plot(diff(ts1))
acf2(diff(ts1))
sarima(ts1,0,1,1)
sarima.for(ts1,4,0,1,1)
plot.ts(SMA(ts1,n=3))
ts2=HoltWinters(ts1, beta=FALSE, gamma=FALSE, l.start=15)
plot(forecast(ts2,h=4))
